stages:
  - build-eardo
  - build
  - setup
  - deploy

variables:
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  DOCKER_TLS_CERTDIR: ""
  BASE: ensembl-k8s-manifests/genome-browser
  NFS_SERVER: ${HL_NFS_SERVER_CODON}
  NFS_PATH: ${HL_NFS_PATH_CODON}

.build-eardo:
  stage: build-eardo
  image: dockerhub.ebi.ac.uk/ensembl-web/peregrine-eard:latest

  script:
    - cd backend-server
    - ./build-begs.sh

  artifacts:
    name: eardo_artifacts
    paths:
      - backend-server/egs-data/begs/render16.eardo

.base-be-rules:
  rules:
    - if: '$CI_DEPLOY_FREEZE == null'
      changes:
        - backend-server/**/*
      when: on_success
    - when: never

.base-be-deploy-rules:
  rules:
    - if: '$CI_DEPLOY_FREEZE == null && $CI_COMMIT_BRANCH == "master"'
      changes:
        - backend-server/**/*
      when: manual
    - when: never

.base-be-deploy-rules-branches:
  rules:
    - if: '$CI_DEPLOY_FREEZE == null && ( $CI_COMMIT_BRANCH != "master" || $CI_COMMIT_BRANCH != "staging" )'
      changes:
        - backend-server/**/*
      when: on_success
    - when: never

.build_backend:
  extends: .base-be-rules
  stage: build
  image: docker
  services:
    - docker:dind

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd backend-server

  script:
    - docker build -t ${DOCKER_IMAGE} --no-cache .
    - docker push ${DOCKER_IMAGE}
    - docker rmi ${DOCKER_IMAGE}
    - docker logout $CI_REGISTRY

.deploy_backend_base:
  stage: deploy
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:latest
  script:
    # Download kustomize manifests and update nfs server/path
    - git clone --depth 1 --branch k8s123-migration https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests.git
    - sed -i "s#<NFS_SERVER>#${NFS_SERVER}#g" ${BASE}/hi/nfs-deployment.patch.yaml
    - sed -i "s#<NFS_PATH>#${NFS_PATH}#g" ${BASE}/hi/nfs-deployment.patch.yaml
    - sed -i "s#<NFS_SERVER>#${NFS_SERVER}#g" ${BASE}/lo/nfs-deployment.patch.yaml
    - sed -i "s#<NFS_PATH>#${NFS_PATH}#g" ${BASE}/lo/nfs-deployment.patch.yaml
    # Update docker image
    - cd ${BASE}/deploy
    - kustomize edit set image DOCKER_IMAGE=${DOCKER_IMAGE}
    # Build hi/lo deployment/configmap manifests and apply
    - kustomize build . | kubectl apply -f -

.deploy_backend:
  extends:
    - .deploy_backend_base
    - .base-be-deploy-rules

.deploy_backend_review:
  extends:
    - .deploy_backend_base
    - .base-be-deploy-rules-branches

BE-eardo:
  extends: .build-eardo

BE-Docker:
  extends: .build_backend

Production:WP40:HL:
  extends: .deploy_backend
  environment:
    name: wp40-hl-prod

Production:WP41:HX:
  extends: .deploy_backend
  environment:
    name: wp41-hx-prod

Staging:WP40:HL:
  extends: .deploy_backend
  environment:
    name: wp40-hl-staging

Internal:WP40:HL:
  extends: .deploy_backend
  environment:
    name: wp40-hl-internal

Dev:WP51:HL:
  extends: .deploy_backend
  environment:
    name: wp51-hl-development

Review:WP51:HL:
  extends: .deploy_backend_review
  environment:
    name: wp51-hl-development
    kubernetes:
      namespace: ${CI_COMMIT_REF_SLUG}

SetupReview:WP51:HL:
  stage: setup
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:latest
  environment:
    name: wp51-hl-development
    kubernetes:
      namespace: ${CI_COMMIT_REF_SLUG}
  rules: # Run only when a new branch is created
    - if: $CI_PIPELINE_SOURCE == "push" && 
          $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000"
      when: on_success
    - when: never
  before_script:
    # Create review namespace and remove existing review GB ingress
    - kubectl -n ensembl-dev create namespace ${CI_COMMIT_REF_SLUG} || true
    - kubectl -n ensembl-dev delete ingress genome-browser-server-ingress-hi-${CI_COMMIT_REF_SLUG} || true
    - kubectl -n ensembl-dev delete ingress genome-browser-server-ingress-lo-${CI_COMMIT_REF_SLUG} || true
  script:
    # Download kustomize manifests and update nfs server/path
    - git clone --depth 1 --branch k8s123-migration-gb https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests.git
    # Prepare/apply memcached, gb hi/lo service and ingress manifests
    - cd ensembl-k8s-manifests
    - kubectl apply -f genome-browser/memcached/configmap.yaml
    - kubectl apply -f genome-browser/memcached/deployment.yaml
    - kubectl apply -f genome-browser/memcached/service.yaml
    - ls genome-browser/review
    - kubeclt apply -f genome-browser/review/sources-toml-configmap.yaml
    - kubeclt apply -f genome-browser/base/secrets.yaml
    - cp genome-browser/review/hi/svc/*.yaml ./ # kustomize restrictions workaround
    - kubectl apply -k .
    - cp genome-browser/review/lo/svc/*.yaml ./
    - kubectl apply -k .
    - cp review-setup/ingress-host.patch.yaml ./
    - sed -i "s#<HOST>#${CI_COMMIT_REF_SLUG}.review.ensembl.org#g" ingress-host.patch.yaml
    - cp genome-browser/review/hi/*.yaml ./
    - kubectl apply -k .
    - cp genome-browser/review/lo/*.yaml ./
    - kubectl apply -k .
