stages:
  - build-eardo
  - build
  - deploy

variables:
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  DOCKER_TLS_CERTDIR: ""
  BASE: backend-server/k8s/base

.build-eardo:
  stage: build-eardo
  image: dockerhub.ebi.ac.uk/ensembl-web/peregrine-eard:latest

  script:
    - cd backend-server
    - ./build-begs.sh

  artifacts:
    name: eardo_artifacts
    paths:
      - backend-server/egs-data/begs/render16.eardo

.base-be-rules:
  rules:
    - changes:
      - backend-server/**/*

.base-be-deploy-rules:
  rules:
    - if: '$CI_DEPLOY_FREEZE == null && $CI_COMMIT_BRANCH == "master"'
      changes:
        - backend-server/**/*
      when: manual
    - when: never

.base-be-deploy-rules-branches:
  rules:
    - if: '$CI_COMMIT_BRANCH != "master" || $CI_COMMIT_BRANCH != "staging"'
      changes:
        - backend-server/**/*
      when: on_success
    - when: never

.build_backend:
  extends: .base-be-rules
  stage: build
  image: docker
  services:
    - docker:dind

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd backend-server

  script:
    - docker build -t ${DOCKER_IMAGE} --no-cache .
    - docker push ${DOCKER_IMAGE}
    - docker rmi ${DOCKER_IMAGE}
    - docker logout $CI_REGISTRY

  needs: ["BE-eardo"]

.deploy_backend:
  extends: .base-be-deploy-rules
  stage: deploy
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:0.4
  before_script:
    - sed -i "s#<NFS_SERVER>#${NFS_SERVER}#g" ${BASE}/hi/patch.yaml
    - sed -i "s#<NFS_PATH>#${NFS_PATH}#g" ${BASE}/hi/patch.yaml
    - sed -i "s#<NFS_SERVER>#${NFS_SERVER}#g" ${BASE}/lo/patch.yaml
    - sed -i "s#<NFS_PATH>#${NFS_PATH}#g" ${BASE}/lo/patch.yaml

  script:
    # Update hi configuration
    - cd ${BASE}/hi
    - kustomize edit set image DOCKER_IMAGE=${DOCKER_IMAGE}
    - kustomize edit add label "app":"new-genome-browser-server"
    - kustomize edit set label "gbtype":"hi"
    - kustomize edit set namesuffix -- -hi
    - cd -

    # Update lo configuration
    - cd ${BASE}/lo
    - kustomize edit set image DOCKER_IMAGE=${DOCKER_IMAGE}
    - kustomize edit add label "app":"new-genome-browser-server"
    - kustomize edit set label "gbtype":"lo"
    - kustomize edit set namesuffix -- -lo
    - cd -

    # Update hi/lo configuration
    - kustomize build ${BASE}/hi | kubectl apply -f -
    - kustomize build ${BASE}/lo | kubectl apply -f -

  needs: ["BE-Docker"]

.deploy_backend-newk8s:
  extends: .base-be-deploy-rules
  stage: deploy
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:latest
  before_script:
    - git clone https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests.git
    - git -C ensembl-k8s-manifests/ checkout k8s123-migration
    - sed -i "s#<NFS_SERVER>#${NFS_SERVER}#g" ${BASE}/hi/nfs-deployment.patch.yaml
    - sed -i "s#<NFS_PATH>#${NFS_PATH}#g" ${BASE}/hi/nfs-deployment.patch.yaml
    - sed -i "s#<NFS_SERVER>#${NFS_SERVER}#g" ${BASE}/lo/nfs-deployment.patch.yaml
    - sed -i "s#<NFS_PATH>#${NFS_PATH}#g" ${BASE}/lo/nfs-deployment.patch.yaml

  script:
    # Update docker image
    - cd ${BASE}/deploy
    - kustomize edit set image DOCKER_IMAGE=${DOCKER_IMAGE}

    # Update hi/lo configuration and apply
    - kustomize build . | kubectl apply -f -


  needs: ["BE-Docker"]
  
.deploy_backend_branches:
  extends: .base-be-deploy-rules-branches
  environment:
    name : wp-hx-dev
  stage: deploy
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:0.4
  variables:
    BASE: backend-server/k8s/overlays/review
    NFS_SERVER: ${HX_NFS_SERVER}
    NFS_PATH: ${HX_NFS_PATH}
  before_script:
    - sed -i "s#<NFS_SERVER>#${NFS_SERVER}#g" ${BASE}/hi/patch.yaml
    - sed -i "s#<NFS_PATH>#${NFS_PATH}#g" ${BASE}/hi/patch.yaml
    - sed -i "s#<NFS_SERVER>#${NFS_SERVER}#g" ${BASE}/lo/patch.yaml
    - sed -i "s#<NFS_PATH>#${NFS_PATH}#g" ${BASE}/lo/patch.yaml

  dependencies:
    - BE-eardo

  script:
    # Update hi configuration
    - cd ${BASE}/hi
    - kustomize edit set image DOCKER_IMAGE=${DOCKER_IMAGE}
    - kustomize edit add label "app":"new-genome-browser-server"
    - kustomize edit add label "gbtype":"${CI_COMMIT_REF_SLUG}-hi"
    - kustomize edit set namesuffix -- -${CI_COMMIT_REF_SLUG}-hi
    - cd -

    # Update lo configuration
    - cd ${BASE}/lo
    - kustomize edit set image DOCKER_IMAGE=${DOCKER_IMAGE}
    - kustomize edit add label "app":"new-genome-browser-server"
    - kustomize edit add label "gbtype":"${CI_COMMIT_REF_SLUG}-lo"
    - kustomize edit set namesuffix -- -${CI_COMMIT_REF_SLUG}-lo
    - cd -

    # Update hi/lo configuration
    - kustomize build ${BASE}/hi | kubectl apply -f -
    - kustomize build ${BASE}/lo | kubectl apply -f -

BE-eardo:
  extends: .build-eardo

BE-Docker:
  extends: .build_backend

HX:Branches:
  extends: .deploy_backend_branches

HX:Dev:
  extends: .deploy_backend
  environment:
    name : wp-hx-dev
  variables:
    BASE: backend-server/k8s/overlays/dev
    NFS_SERVER: ${HX_NFS_SERVER}
    NFS_PATH: ${HX_NFS_PATH}

Production:WP40:HL:
  extends: .deploy_backend-newk8s
  environment:
    name: wp40-hl-prod
  variables:
    BASE: ensembl-k8s-manifests/genome-browser
    NFS_SERVER: ${HL_NFS_SERVER_CODON}
    NFS_PATH: ${HL_NFS_PATH_CODON}

Production:WP41:HX:
  extends: .deploy_backend-newk8s
  environment:
    name: wp41-hx-prod
  variables:
    BASE: ensembl-k8s-manifests/genome-browser
    NFS_SERVER: ${HL_NFS_SERVER_CODON}
    NFS_PATH: ${HL_NFS_PATH_CODON}

Staging:WP40:HL:
  extends: .deploy_backend-newk8s
  environment:
    name: wp40-hl-staging
  variables:
    BASE: ensembl-k8s-manifests/genome-browser
    NFS_SERVER: ${HL_NFS_SERVER_CODON}
    NFS_PATH: ${HL_NFS_PATH_CODON}

Internal:WP40:HL:
  extends: .deploy_backend-newk8s
  environment:
    name: wp40-hl-internal
  variables:
    BASE: ensembl-k8s-manifests/genome-browser
    NFS_SERVER: ${HL_NFS_SERVER_CODON}
    NFS_PATH: ${HL_NFS_PATH_CODON}

Dev:WP40:HL:
  extends: .deploy_backend-newk8s
  environment:
    name: wp40-hl-development
  variables:
    BASE: ensembl-k8s-manifests/genome-browser
    NFS_SERVER: ${HL_NFS_SERVER_CODON}
    NFS_PATH: ${HL_NFS_PATH_CODON}

Dev:WP41:HX:
  extends: .deploy_backend-newk8s
  environment:
    name: wp41-hx-development
  variables:
    BASE: ensembl-k8s-manifests/genome-browser
    NFS_SERVER: ${HX_NFS_SERVER_CODON}
    NFS_PATH: ${HX_NFS_PATH_CODON}
