FROM python:3.8

# maintainer of the image
LABEL maintainer="ensembl-webteam@ebi.ac.uk"

# Environment variable
ENV PYTHONUNBUFFERED TRUE

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY app/ /usr/src/app/
COPY requirements.txt /usr/src/app/

RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 3333

CMD ["uvicorn","--host", "0.0.0.0", "--port", "3333","main:app"]