include_files = [
    "tracks-include.toml"
]

from_bundles = [
    "boot",
    "test"
]

[include.gene.general]
triggers = [
    ["track","gene-pc-fwd"],
    ["track","gene-pc-rev"],
    ["track","gene-other-fwd"],
    ["track","gene-other-rev"]
]

[include.gene.settings]
focus-gene = ["track","focus","item","gene"]
pc-fwd-several = ["track","gene-pc-fwd","several"]
pc-rev-several = ["track","gene-pc-rev","several"]
other-fwd-several = ["track","gene-other-fwd","several"]
other-rev-several = ["track","gene-other-rev","several"]
pc-fwd-label = ["track","gene-pc-fwd","label"]
pc-rev-label = ["track","gene-pc-rev","label"]
other-fwd-label = ["track","gene-other-fwd","label"]
other-rev-label = ["track","gene-other-rev","label"]
pc-fwd = ["track","gene-pc-fwd"]
pc-rev = ["track","gene-pc-rev"]
other-fwd = ["track","gene-other-fwd"]
other-rev = ["track","gene-other-rev"]
pc-fwd-name = ["track","gene-pc-fwd","name"]
pc-rev-name = ["track","gene-pc-rev","name"]
other-fwd-name = ["track","gene-other-fwd","name"]
other-rev-name = ["track","gene-other-rev","name"]
expanded = ["buttons"]

[include.transcript.settings]
pc-fwd-several = ["track","gene-pc-fwd","several"]
pc-rev-several = ["track","gene-pc-rev","several"]
other-fwd-several = ["track","gene-other-fwd","several"]
other-rev-several = ["track","gene-other-rev","several"]
pc-fwd-transcript-label = ["track","gene-pc-fwd","transcript-label"]
pc-rev-transcript-label = ["track","gene-pc-rev","transcript-label"]
other-fwd-transcript-label = ["track","gene-other-fwd","transcript-label"]
other-rev-transcript-label = ["track","gene-other-rev","transcript-label"]

[include.focus-gene.general]
triggers = [
    ["track","focus","item","gene"]
]

[include.focus-gene.settings]
focus-gene = ["track","focus","item","gene"]
focus = ["track","focus"]
focus-gene-label = ["track","focus","label"]
focus-transcript-label = ["track","focus","transcript-label"]
several = ["track","focus","several"]
enabled-transcripts = ["track","focus","enabled-transcripts"]
name = ["track","focus","name"]
expanded = ["buttons"]

#
# Tracks
#

#
# Genes/Transcripts
#

[track.gene-overview]
scales = [23,100,6]
include=["gene","general"]

[track.gene]
scales = [19,22,4]
include=["gene","general"]

[track.transcript]
scales = [9,18,6]
include=["transcript","gene","general"]

[track.zoomed-transcript-no-letters.general]
program_name = "zoomed-transcript"
scales = [7,8,2]
include=["transcript","gene","general"]

[track.zoomed-transcript-no-letters.values]
scale-no-letters = true

[track.zoomed-transcript-letters]
program_name = "zoomed-transcript"
scales = [0,6,7]
include=["transcript","gene","general"]

[track.focus-gene-dots]
scales = [1,66,1]
include=["focus-gene","general"]

[track.focus-gene]
scales = [19,66,4]
include=["focus-gene","general"]

[track.focus-transcript]
scales = [9,18,6]
include=["focus-gene","general"]

[track.focus-zoomed-transcript-letters]
program_name = "focus-zoomed-transcript"
scales = [0,7,8]
include=["focus-gene","general"]

[track.focus-zoomed-transcript-no-letters.general]
program_name = "focus-zoomed-transcript"
scales = [8,8,1]
include=["focus-gene","general"]

[track.focus-zoomed-transcript-no-letters.values]
scale-no-letters = true

#
# Frame
#

[track.framing]
include = ["general"]
triggers = [["track"]]
scales = [1,100,1]

#
# Ruler
#

[track.ruler.general]
include = ["general"]
scales = [0,100,1]
triggers = [["ruler"]]

[track.ruler.settings]
one_based = ["ruler","one_based"]

#
# Focus locations
#

[track.focus-region.general]
scales = [0,99,1]
include = ["general"]
triggers = [
    ["track","focus","item","location"]
]

[track.focus-region.settings]
region = ["track","focus","item","location"]

#
# %GC
#

[track.gc.general]
include = ["general"]
scales = [0,100,3]
triggers = [["track","gc"]]

[track.gc.settings]
name = ["track","gc","name"]

#
# Variants
#

[track.variant-1000genomes.general]
include = ["general"]
scales = [1,100,4]
triggers = [["track","variant-1000genomes"]]
tags= "#has-variants"

[track.variant-1000genomes.settings]
name = ["track","variant-1000genomes","name"]

[track.variant-dbsnp.general]
include = ["general"]
scales = [1,100,4]
triggers = [["track","variant-dbsnp"]]
tags = "#has-variants"

[track.variant-dbsnp.settings]
name = ["track","variant-dbsnp","name"]

[track.variant-clinvar.general]
include = ["general"]
scales = [1,100,4]
triggers = [["track","variant-clinvar"]]
tags = "#has-variants"

[track.variant-clinvar.settings]
name = ["track","variant-clinvar","name"]

[track.variant-gwas.general]
include = ["general"]
scales = [1,100,4]
triggers = [["track","variant-gwas"]]
tags = "#has-variants"

[track.variant-gwas.settings]
name = ["track","variant-gwas","name"]

[track.variant-eva.general]
include = ["general"]
scales = [1,100,4]
triggers = [["track","variant-eva"]]
tags = "#has-variants"

[track.variant-eva.settings]
name = ["track","variant-eva","name"]

[track.variant-sgrp.general]
include = ["general"]
scales = [1,100,4]
triggers = [["track","variant-sgrp"]]
tags = "#has-variants"

[track.variant-sgrp.settings]
name = ["track","variant-sgrp","name"]

[track.focus-variant.general]
include = ["general"]
scales = [3,5,1]
triggers = [["track","focus","item","variant"]]
tags= "#has-variants"

[track.focus-variant.settings]
focus-variant = ["track","focus","item","variant"]
name = ["track","focus","name"]
label-snv-id = ["track","focus","variant","label-snv-id"]
label-snv-alleles = ["track","focus","variant","label-snv-alleles"]
label-other-id = ["track","focus","variant","label-other-id"]
label-other-alleles = ["track","focus","variant","label-other-alleles"]
show-extents = ["track","focus","variant","show-extents"]

[track.focus-variant-summary.general]
include = ["general"]
scales = [6,100,4]
triggers = [["track","focus","item","variant"]]
tags= "#has-variants"

[track.focus-variant-summary.settings]
focus-variant = ["track","focus","item","variant"]
name = ["track","focus","name"]

[track.focus-variant-dots.general]
scales = [1,66,1]
include=["general"]
triggers = [["track","focus","item","variant"]]

[track.focus-variant-dots.settings]
focus-variant = ["track","focus","item","variant"]

#
# Regulation
#
[track.regulation]
include = ["general"]
scales = [1,100,3]
triggers = [["track","regulation"]]

[track.regulation.settings]
name = ["track","regulation","name"]

#
# Contigs and Sequences
#

[track.contig-shimmer.general]
include = ["general"]
program_name = "contig"
scales = [26,100,3]
triggers = [["track","contig"]]

[track.contig-shimmer.values]
shimmer = true

[track.contig.general]
include = ["general"]
scales = [9,25,3]
triggers = [["track","contig"]]

[track.contig.settings]
name = ["track","contig","name"]

[track.sequence-no-letters.general]
include = ["general"]
program_name = "zoomed-seq"
scales = [7,8,2]
triggers = [["track","contig"]]

[track.sequence-no-letters.settings]
name = ["track","contig","name"]

[track.sequence-no-letters.values]
scale-no-letters = true

[track.sequence.general]
include = ["general"]
program_name = "zoomed-seq"
scales = [0,6,3]
triggers = [["track","contig"]]

[track.sequence.settings]
name = ["track","contig","name"]


#
# Expansions
#

[expansion.test]
channel = ["ensembl","main"]
name = "test"
triggers = [
    ["track","expand"]
]
run = "test"
