[package]
name = "earp_assembler"
version = "0.0.0"
authors = ["Dan Sheppard <dan@ebi.ac.uk>"]
edition="2018"

[dependencies]
earp_runtime= { path = "../earp-runtime" }
futures="*"
pest="*"
pest_consume="*"
pest_derive="*"
minicbor={ version="*", features=["std"] }