stages:
  - build_docker
  - deploy

# Builds wasm files
.build_wasm:
  stage: build_docker
  image: rust:1.57

  script:
    - echo "Running build"
    - ./build.sh
    - ls pkg/

  rules:
    - if: '$CI_DEPLOY_FREEZE == null && $CI_COMMIT_BRANCH == "multi-project-build"'
      changes: 
        - peregrine-ensembl/*

Build-WASM:
  extends: .build_wasm
