stages:
  - build_docker
  - trigger_npm_build

# Builds wasm files
.build_wasm:
  stage: build_docker
  image: rust:1.57

  before_script:
    - cd peregrine-ensembl
    - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

  script:
    - RUSTFLAGS="--cfg=console --cfg=force_show_incoming"
    - wasm-pack build --target web --release
    - ls pkg/

  rules:
    - if: '$CI_DEPLOY_FREEZE == null'
      changes: 
        - peregrine-ensembl/*

  artifacts:
    name: build_wasm_artifacts
    paths:
      - peregrine-ensembl/pkg/

Build-WASM:
  extends: .build_wasm

# Build node package in downstream pipeline
Build-npm:dev:
  stage: trigger_npm_build
  variables:
    UPSTREAM_BRANCH: $CI_COMMIT_REF_NAME

  trigger:
    project: ensembl-web/ensembl-genome-browser
    branch: dynamic-branch

  rules:
    - if: '$CI_DEPLOY_FREEZE == null && $CI_COMMIT_BRANCH != "master"'
      changes:
        - peregrine-ensembl/*

# Build node package in downstream pipeline
Build-npm:Live:
  stage: trigger_npm_build
  variables:
    UPSTREAM_BRANCH: $CI_COMMIT_REF_NAME

  trigger:
    project: ensembl-web/ensembl-genome-browser
    branch: main

  rules:
    - if: '$CI_DEPLOY_FREEZE == null && $CI_COMMIT_BRANCH == "master"'
      changes:
        - peregrine-ensembl/*
