stages:
  - build_docker
  - deploy

# Builds wasm files
.build_wasm:
  stage: build_docker
  image: rust:1.57

  before_script:
    - cd peregrine-ensembl
    - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

  script:
    - RUSTFLAGS="--cfg=console --cfg=force_show_incoming"
    - wasm-pack build --target web --dev
    - ls pkg/

  rules:
    - if: '$CI_DEPLOY_FREEZE == null && $CI_COMMIT_BRANCH == "multi-project-build"'
      changes: 
        - peregrine-ensembl/*

Build-WASM:
  extends: .build_wasm

# Build node package
Build-npm:
  stage: deploy
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:0.4

  script:
    - echo "Trigger Build node package here"


  rules:
    - if: '$CI_DEPLOY_FREEZE == null && $CI_COMMIT_BRANCH == "multi-project-build"'
      changes: 
        - peregrine-ensembl/*

