[sources.bell]
volume=0.1
file="bell.ogg"
chrome=true

[sources.chevron-left]
width=32
height=32
file="chevron-left.png"
scale=200

[sources.chevron-right]
width=32
height=32
file="chevron-right.png"
scale=200

[sources.chevron-dark-left]
width=32
height=32
file="chevron-dark-left.png"
scale=200

[sources.chevron-dark-right]
width=32
height=32
file="chevron-dark-right.png"
scale=200
