include_files = [
    "tracks-include.toml"
]

from_bundles = [
    "boot",
    "test"
]

[include.gene.general]
triggers = [
    ["track","gene-pc-fwd"],
    ["track","gene-pc-rev"],
    ["track","gene-other-fwd"],
    ["track","gene-other-rev"]
]
extra = [ # togo
    ["track","focus","item","gene"],
    ["settings"],
    ["focus"],
    ["track","focus"],
    ["buttons","gene"]
]
tags = ["gene"]

[include.gene.settings]
focus-gene = ["track","focus","item","gene"]
pc-fwd-several = ["track","gene-pc-fwd","several"]
pc-rev-several = ["track","gene-pc-rev","several"]
other-fwd-several = ["track","gene-other-fwd","several"]
other-rev-several = ["track","gene-other-rev","several"]
pc-fwd-label = ["track","gene-pc-fwd","label"]
pc-rev-label = ["track","gene-pc-rev","label"]
other-fwd-label = ["track","gene-other-fwd","label"]
other-rev-label = ["track","gene-other-rev","label"]
pc-fwd = ["track","gene-pc-fwd"]
pc-rev = ["track","gene-pc-rev"]
other-fwd = ["track","gene-other-fwd"]
other-rev = ["track","gene-other-rev"]
pc-fwd-name = ["track","gene-pc-fwd","name"]
pc-rev-name = ["track","gene-pc-rev","name"]
other-fwd-name = ["track","gene-other-fwd","name"]
other-rev-name = ["track","gene-other-rev","name"]

[include.transcript.settings]
pc-fwd-several = ["track","gene-pc-fwd","several"]
pc-rev-several = ["track","gene-pc-rev","several"]
other-fwd-several = ["track","gene-other-fwd","several"]
other-rev-several = ["track","gene-other-rev","several"]


[include.focus-gene.general]
triggers = [
    ["track","focus","item","gene"]
]
extra = [ # togo
    ["settings"],
    ["focus"],
    ["track","focus"],
    ["buttons","gene"]
]
tags = ["gene"]

[include.focus-gene.settings]
focus-gene = ["track","focus","item","gene"]
focus = ["track","focus"]
focus-gene-label = ["track","focus","label"]
focus-transcript-label = ["track","focus","transcript-label"]
several = ["track","focus","several"]
enabled-transcripts = ["track","focus","enabled-transcripts"]
name = ["track","focus","name"]

#
# Tracks
#

#
# Genes/Transcripts
#

[track.gene-overview]
scales = [23,100,6]
include=["gene","general"]

[track.gene]
scales = [19,22,4]
include=["gene","general"]

[track.transcript]
scales = [9,18,6]
include=["transcript","gene","general"]

[track.zoomed-transcript-no-letters.general] # to .general for TOML spec
program_name = "zoomed-transcript"
scales = [8,8,1]
include=["transcript","gene","general"]
set = [ # togo
    { path = ["scale","no-letters"], value = true }
]

[track.zoomed-transcript-no-letters.values]
no-letters = true

[track.zoomed-transcript-letters]
program_name = "zoomed-transcript"
scales = [0,7,8]
include=["transcript","gene","general"]

[track.focus-transcript]
scales = [9,60,60]
include=["focus-gene","general"]

[track.focus-zoomed-transcript-letters]
program_name = "focus-zoomed-transcript"
scales = [0,7,8]
include=["focus-gene","general"]

[track.focus-zoomed-transcript-no-letters.general]
program_name = "focus-zoomed-transcript"
scales = [8,8,1]
include=["focus-gene","general"]
set = [ # togo
    ["scale","no-letters"]
]

[track.focus-zoomed-transcript-no-letters.values]
no-letters = true

#
# Frame
#

[track.framing]
include = ["general"]
triggers = [["track"]]
scales = [1,100,1]

#
# Ruler
#

[track.ruler]
include = ["general"]
scales = [0,100,1]
triggers = [["ruler"]]

#
# %GC
#

[track.gc.general]
include = ["general"]
scales = [0,100,3]
triggers = [["track","gc"]]
tags=["gc"]

[track.gc.settings]
name = ["track","gc","name"]

#
# Variants
#

[track.variant.general]
include = ["general"]
scales = [1,100,4]
triggers = [["track","variant"]]
tags=["variant"]

[track.variant.settings]
name = ["track","variant","name"]

#
# Contigs and Sequences
#

[track.contig-shimmer.general]
include = ["general"]
program_name = "contig"
scales = [26,100,3]
triggers = [["track","contig"]]
extra=[["settings"]] #togo
tags=["contig"]
set=[ # togo
    ["scale","shimmer"]
]

[track.contig-shimmer.values]
shimmer = true

[track.contig.general]
include = ["general"]
scales = [9,25,3]
triggers = [["track","contig"]]
extra = [["settings"]]
tags = ["contig"]

[track.contig.settings]
name = ["track","contig","name"]

[track.sequence.general]
include = ["general"]
program_name = "zoomed-seq"
scales = [0,8,3]
triggers = [["track","contig"]]
tags=["contig"]

[track.sequence.settings]
name = ["track","contig","name"]


#
# Expansions
#

[expansion.test]
channel = ["ensembl","main"]
name = "test"
triggers = [
    ["track","expand"]
]
run = "test"
