[gene-biotype.label]
3prime_overlapping_ncrna="3prime overlapping ncRNA"
antisense="antisense"
antisense_rna="antisense RNAAlso referred to as antisense transcript"
guide_rna="guide RNA"
ig_c="IG C"
ig_c_pseudogene="IG C pseudogene"
ig_d="IG D"
ig_j="IG J"
ig_j_pseudogene="IG J pseudogene"
ig_pseudogene="IG pseudogene"
ig_v="IG V"
ig_v_pseudogene="IG V pseudogene"
lncrna="lncRNA"
mirna="miRNA"
misc_rna="misc RNA"
mt_rrna="mt rRNA"
mt_trna="mt tRNA"
ncrna="ncRNAC.elegans"
nontranslating_cds="nontranslating CDS"
pirna="piRNA geneC.elegans"
polymorphic_pseudogene="polymorphic pseudogene"
pre_mirna="pre miRNAThis is the pre miRNA information extracted from FlyBase annotations distinctive from the miRNA form for the same gene model"
processed_pseudogene="processed pseudogene"
protein_coding="protein coding"
pseudogene="pseudogene"
ribozyme="ribozyme"
rna_subunit_of_the_rnase="RNA subunit of the RNaseWheat"
rnase_p_rna="RNase P RNAIts best characterized activity is the generation of mature 5 prime ends of tRNAs by cleaving the 5 prime leader elements of precursor-tRNAs."
rrna="rRNA"
rrna_pseudogene="rRNA pseudogene"
scarna="scaRNA"
scrna="scRNA"
sense_intronic="sense intronic geneGRCh37"
sense_overlapping="sense overlapping geneGRCh37"
snorna="snoRNA"
snrna="snRNA"
srna="sRNA"
plant_signal_recognition_particle_rna="plant signal recognition particle RNAWheat"
tec="TEC"
tr_c="TR C"
tr_d="TR D"
tr_j="TR J"
tr_j_pseudogene="TR J pseudogene"
tr_v="TR V"
tr_v_pseudogene="TR V pseudogene"
transcribed_processed_pseudogene="transcribed processed pseudogene"
transcribed_unitary_pseudogene="transcribed unitary pseudogene"
transcribed_unprocessed_pseudogene="transcribed unprocessed pseudogene"
translated_processed_pseudogene="translated processed pseudogene"
translated_unprocessed_pseudogene="translated unprocessed pseudogene"
transposable_element="transposable elementD.melanogaster"
trna="tRNA geneC.elegans"
trna_pseudogene="tRNA pseudogeneNon-functional is defined as its transcription is prevented due to one or more mutatations."
unitary_pseudogene="unitary pseudogene"
unprocessed_pseudogene="unprocessed pseudogene"
vault_rna="vault RNA"

[tr-biotype.label]
3prime_overlapping_ncrna="3prime overlapping ncRNA"
antisense="antisense"
antisense_rna="antisense RNA"
guide_rna="guide RNA"
ig_c="IG C"
ig_c_pseudogene="IG C pseudogene"
ig_d="IG D"
ig_j="IG J"
ig_j_pseudogene="IG J pseudogene"
ig_pseudogene="IG pseudogene"
ig_v="IG V"
ig_v_pseudogene="IG V pseudogene"
lincrna="lincRNA"
lncrna="lncRNA"
mirna="miRNA"
misc_rna="misc RNA"
mt_rrna="mt rRNA"
mt_trna="mt tRNA"
ncrna="ncRNA"
nontranslating_cds="nontranslating CDS"
pirna="piRNA"
polymorphic_pseudogene="polymorphic pseudogene"
pre_mirna="pre miRNA"
processed_pseudogene="processed pseudogene"
protein_coding="protein coding"
pseudogene="pseudogene"
ribozyme="ribozyme"
rna_subunit_of_the_rnase="RNA subunit of the RNase"
rnase_p_rna="RNase P RNA"
rrna="rRNA"
rrna_pseudogene="rRNA pseudogene"
scarna="scaRNA"
scrna="scRNA"
sense_intronic="sense intronic"
sense_overlapping="sense overlapping"
snorna="snoRNA"
snrna="snRNA"
srna="sRNA"
plant_signal_recognition_particle_rna="plant signal recognition particle RNA"
tec="TEC"
tr_c="TR C"
tr_d="TR D"
tr_j="TR J"
tr_j_pseudogene="TR J pseudogene"
tr_v="TR V"
tr_v_pseudogene="TR V pseudogene"
transcribed_processed_pseudogene="transcribed processed pseudogene"
transcribed_unitary_pseudogene="transcribed unitary pseudogene"
transcribed_unprocessed_pseudogene="transcribed unprocessed pseudogene"
translated_processed_pseudogene="translated processed pseudogene"
translated_unprocessed_pseudogene="translated unprocessed pseudogene"
transposable_element="transposable element"
trna="tRNA"
trna_pseudogene="tRNA pseudogene"
unitary_pseudogene="unitary pseudogene"
unprocessed_pseudogene="unprocessed pseudogene"
vault_rna="vault RNA"

[designation.label]
mane_select="MANE Select"
mane_plus_clinical="MANE Plus Clinical"
mane="MANE"
normal=""
canonical="Ensembl canonical"
