[source]
driver = "s3"
url = "https://ensembl-2020-gb-flatfiles.s3.eu-west-2.amazonaws.com/upload-20210808/"

# Wheat contig file is broken
[redirect.data.contig.triticum_aestivum_GCA_900519105]
upstream=""
