[source]
driver = "s3"
url="http://nginx/upload-20220829/"

#[redirect.data]
#upstream="http://52.56.215.72:3333/api/data"

#[redirect.jump]
#upstream="http://52.56.215.72:3333/api/data"

[redirect.metric]
upstream="http://52.56.215.72:3333/api/data"
