[source.apple]
driver = "file"
root = "/usr/data/newsite/internal/genome_browser/8"
refget_url = "http://ensembl-refget-proxy-svc:8083/api/sequence/"
min_version = 16

[apis]
track_api = "http://ensembl-track-api-svc:8012"
