[source]
driver = "s3"
url = "https://ensembl-2020-gb-flatfiles.s3.eu-west-2.amazonaws.com/upload-20220829/"

[redirect.data]
upstream="http://52.56.215.72:3333/api/data"

[redirect.jump]
upstream="http://52.56.215.72:3333/api/data"

[redirect.metric]
upstream="http://52.56.215.72:3333/api/data"
