[source.apple]
driver = "s3"
url = "http://nginx/upload-20220829/"
refget_url = "https://beta.ensembl.org/api/refget/sequence/"
min_version = 16

[redirect.data]
upstream = "http://52.56.215.72:3333/api/data"

[redirect.jump]
upstream = "http://52.56.215.72:3333/api/data"

[apis]
track_api = "https://beta.ensembl.org/api/tracks/"
