[source.apple]
driver = "s3"
url = "http://ensembl-2020-gb-flatfiles.s3.eu-west-2.amazonaws.com/"
refget_url = "https://dev-2020.ensembl.org/api/refget/sequence/"
metadata_url = "https://dev-2020.ensembl.org/api/metadata/"

min_version = 16

[apis]
track_api = "https://staging-2020.ensembl.org/api/tracks"
