[source.apple]
driver = "s3"
url="http://nginx/upload-20220829/"
refget_url="https://beta.ensembl.org/api/refget/sequence/"
max_version = 13

[source.banana]
driver = "s3"
url="http://nginx/upload-20220829/"
refget_url="https://beta.ensembl.org/api/refget/sequence/"
min_version = 14
