[source.apple]
driver = "file"
root = "/usr/data/newsite/dev/genome_browser/s3-data"
refget_url="https://beta.ensembl.org/api/refget/sequence/"
max_version = 13

[source.banana]
driver = "file"
root = "/usr/data/newsite/dev/genome_browser/7"
refget_url="https://beta.ensembl.org/api/refget/sequence/"
min_version = 14
