[source.apple]
driver = "file"
root = "/usr/data/newsite/internal/genome_browser/8"
refget_url = "http://ensembl-refget-file-svc:8000/sequence/"
metadata_url = "http://metadata-api-svc:8014/api/metadata/"
min_version = 16

[apis]
track_api = "http://ensembl-track-api-svc:8012"
