[source]
driver = "s3"
url="http://nginx/upload-20210808/"

[redirect.data]
upstream="http://52.56.215.72:3333/api/data"

[redirect.jump]
upstream="http://52.56.215.72:3333/api/data"

[redirect.data.gene]
upstream=""
