[package]
name = "earp_runtime"
version = "0.0.0"
authors = ["Dan Sheppard <dan@ebi.ac.uk>"]
edition="2018"

[features]
test = []

[dependencies]
futures="*"
minicbor={ version="*", features=["std","half","alloc"] }
