set = "ensembl-webteam/core"
name = "zoomed-transcript"
version = 1
description = """

Show the non-focus gene as a set of individual bases of various kinds, denoting exons, introns, etc.
Uses many settings to do so (see below).

Uses data sequences from transcript endpoint:
- gene_id
- gene_id_version
- gene_names
- gene_descs
- starts
- lengths
- transcripts_starts
- transcripts_lengths
- gene_designation_keys
- gene_designation_values
- transcript_designation_keys
- transcript_designation_values
- gene_biotypes_keys
- gene_biotypes_calues
- strands
- transcript_id
- transcript_id_version
- transcript_biotypes_keys
- transcript_biotypes_values
- transcript_counts
- thicks_starts
- thicks_lengths
- transcript_exon_counts
- transcript_counts
- transcript_exon_starts
- transcript_exon_lengths

Also uses the following data sequences from the zoomed-seq endpoint:
- sequence
- sequence_start

"""

[setting.focus-gene]
description = """

Which gene is currently the focus gene (if any)? Object with keys "genome_id" and "item_id"
identifying current focus gene, if any.

"""

[setting.focus]
description = """

boolean which when true means the focus track is on.

"""

[setting.scale-no-letters]
default = false
description = """

boolean which when true means that no individual base letters will be shown due to the scale.

"""

[setting.pc-fwd-several]
default = false
description = """

boolean: if true show 5 per the mini-toggle setting on the pc-fwd track.

"""

[setting.pc-rev-several]
default = false
description = """

boolean: if true show 5 per the mini-toggle setting on the pc-rev track.

"""

[setting.other-fwd-several]
default = false
description = """

boolean: if true show 5 per the mini-toggle setting on the other-fwd track.

"""

[setting.other-rev-several]
default = false
description = """

boolean: if true show 5 per the mini-toggle setting on the other-rev track.

"""

[setting.pc-fwd-label]
default = true
description = """

boolean: if true show gene label on the pc-fwd track.

"""

[setting.pc-rev-label]
default = true
description = """

boolean: if true show gene label on the pc-rev track.

"""

[setting.other-fwd-label]
default = true
description = """

boolean: if true show gene label on the other-fwd track.

"""

[setting.other-rev-label]
default = true
description = """

boolean: if true show gene label on the other-rev track.

"""

[setting.pc-fwd-transcript-label]
default = true
description = """

boolean: if true show transcript label on the pc-fwd track.

"""

[setting.pc-rev-transcript-label]
default = true
description = """

boolean: if true show transcript label on the pc-rev track.

"""

[setting.other-fwd-transcript-label]
default = true
description = """

boolean: if true show transcript label on the other-fwd track.

"""

[setting.other-rev-transcript-label]
default = true
description = """

boolean: if true show transcript label on the other-rev track.

"""


[setting.pc-fwd]
description = """

boolean: if true show the pc-fwd track.

"""

[setting.pc-rev]
description = """

boolean: if true show the pc-rev track.

"""

[setting.other-fwd]
description = """

boolean: if true show the other-fwd track.

"""

[setting.other-rev]
description = """

boolean: if true show the other-rev track.

"""


[setting.pc-fwd-name]
default = true
description = """

boolean: if true show gene track label on the pc-fwd track.

"""

[setting.pc-rev-name]
default = true
description = """

boolean: if true show gene track label on the pc-rev track.

"""

[setting.other-fwd-name]
default = true
description = """

boolean: if true show gene track label on the other-fwd track.

"""

[setting.other-rev-name]
default = true
description = """

boolean: if true show gene track label on the other-rev track.

"""
