[package]
name = "peregrine_toolkit"
version = "0.0.0"
authors = ["ensembl-webteam@ebi.ac.uk"]
edition = "2018"

[dependencies]
anyhow="*"
js-sys="*"
wasm-bindgen="*"
erased-serde="*"
serde="*"
serde_cbor="*"
serde_derive="*"

[dependencies.commander]
version="*"
path="../commander"

[dependencies.web-sys]
version="*"
features=["console"]
