[package]
name = "dauphin_lib_peregrine"
version = "0.1.0"
authors = ["Dan Sheppard <dan@ebi.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
compile = ["dauphin_compile"]

[dependencies]
anyhow="*"
serde_cbor="*"
url="*"

dauphin_interp = { path = "../dauphin-interp" }
dauphin_compile = { path = "../dauphin-compile", optional = true }

[dev-dependencies]
dauphin_compile = { path = "../dauphin-compile" }
dauphin_test_harness = { path = "../dauphin-test-harness" }

[dependencies.web-sys]
version="*"
features=["console"]

[dependencies.blackbox]
version="*"
path="../blackbox"

[dependencies.peregrine_core]
version="*"
path="../peregrine-core"
