apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-genome-browser-server-deployment
spec:
  template:
    spec:
      containers:
        - name: new-genome-browser-server
          envFrom:
          - configMapRef:
              name: new-genome-browser-server-configmap-hi
      volumes:
        - name: new-genome-browser-server-data-vol
          nfs:
            path: <NFS_PATH>
            server: <NFS_SERVER>