programs = [
    "contig.toml",
    "focus-gene.toml",
    "focus-gene-transcripts.toml",
    "focus-gene-zoomed-transcripts.toml",
    "framing.toml",
    "gc.toml",
    "gene-overview.toml",
    "gene.toml",
    "ruler.toml",
    "test.toml",
    "transcript.toml",
    "variant-1000genomes.toml",
    "variant-dbsnp.toml",
    "zoomed-seq.toml",
    "zoomed-transcript.toml"
]
