set = "ensembl-webteam/core"
name = "variant-1000genomes"
version = 1
description = """

Show variant summary track. Perhaps surprisingly, basically a wiggle track where colours are
used rather than heights.

Uses data sequences from "variant-1000genomes" endpoint:
- values
- range

"""


[setting.name]
default = false
description = """

boolean: if true show track label.

"""
