apiVersion: apps/v1
kind: Deployment
metadata: 
  name: new-genome-browser-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: new-genome-browser-server
    spec:
      imagePullSecrets:
        - name: ensemblweb-pull-secret
      #securityContext:
      #  runAsUser: 3383
      #  runAsGroup: 1135
      containers:
      - name: new-genome-browser-server
        image: DOCKER_IMAGE
        resources:
          requests:
            memory: "250Mi"
          limits:
            memory: "500Mi"
        command: ["uvicorn"]
        args:
          - --host=0.0.0.0
          - --port=3333
          - main:app
          - --workers=$(THREADS)
        ports:
        - containerPort: 3333
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: new-genome-browser-server-configmap
        volumeMounts:
        - mountPath: /usr/data
          name: new-genome-browser-server-data-vol
      volumes:
        - name: new-genome-browser-server-data-vol
          nfs:
            path: <NFS_PATH>
            server: <NFS_SERVER>
