apiVersion: v1
kind: Service
metadata:
  name: new-genome-browser-server-svc
  labels:
    app: new-genome-browser-server-svc
spec:
  selector:
    app: new-genome-browser-server

  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 3333
