name = "focus-zoomed-transcript"
description = """

Show the focus gene as a set of individual bases of various kinds, denoting exons, introns, etc.
Uses many settings to do so (see below).

Uses data sequences from transcript endpoint:
- gene_id
- gene_id_version
- gene_names
- gene_descs
- starts
- lengths
- transcripts_starts
- transcripts_lengths
- gene_designation_keys
- gene_designation_values
- transcript_designation_keys
- transcript_designation_values
- gene_biotypes_keys
- gene_biotypes_calues
- strands
- transcript_id
- transcript_id_version
- transcript_biotypes_keys
- transcript_biotypes_values
- transcript_counts
- thicks_starts
- thicks_lengths
- transcript_exon_counts
- transcript_counts
- transcript_exon_starts
- transcript_exon_lengths

Also uses the following data sequences from the zoomed-seq endpoint:
- sequence
- sequence_start

"""

[setting.focus-gene]
setting = ["track","focus","item","gene"]
description = """

Which gene is currently the focus gene (if any)? Object with keys "genome_id" and "item_id"
identifying current focus gene, if any.

"""

[setting.focus]
setting = ["track","focus"]
description = """

boolean which when true means the focus track is on.

"""

[setting.focus-gene-label]
setting = ["track","focus","label"]
description = """

boolean which when true means the focus track gene labels should be shown.

"""

[setting.focus-transcript-label]
setting = ["track","focus","transcript-label"]
description = """

boolean which when true means the focus track transcript labels should be shown.

"""

[setting.scale-no-labels]
setting = ["scale","no-labels"]
description = """

boolean which when true means that no gene or transcript labels will be shown despite
other settings due to the current scale.

"""

[setting.scale-no-letters]
setting = ["scale","no-letters"]
description = """

boolean which when true means that no individual base letters will be shown due to the scale.

"""

[setting.several]
setting = ["track","focus","several"]
description = """

boolean: if true show 5 per the mini-toggle setting.

"""

[setting.enabled-transcripts]
setting = ["track","focus","enabled-transcripts"]
description = """

list of transcript ids to show in focus track.

"""
