name = "gene"
description = """

Show the non-focus genes as mere blocks when rather zoomed out. (Still with zmenus, labels etc).

Uses data sequences from gene endpoint:
- gene_id
- gene_id_version
- gene_names
- gene_descs
- starts
- lengths
- gene_designation_keys
- gene_designation_values
- gene_biotypes_keys
- gene_biotypes_values
- strands
- designated_transcript_id
- designated_transcript_id_version
- thicks_starts
- thicks_lengths
- designated_transcript_biotypes_keys
- designated_transcript_biotypes_values
- designated_transcript_designations_keys
- designated_transcript_designations_values

"""

[setting.focus-gene]
setting = ["track","focus","item","gene"]
description = """

Which gene is currently the focus gene (if any)? Object with keys "genome_id" and "item_id"
identifying current focus gene, if any.

"""

[setting.pc-fwd-several]
setting = ["track","gene-pc-fwd","several"]
description = """

boolean: if true show 5 per the mini-toggle setting on the pc-fwd track.

"""

[setting.pc-rev-several]
setting = ["track","gene-pc-rev","several"]
description = """

boolean: if true show 5 per the mini-toggle setting on the pc-rev track.

"""

[setting.other-fwd-several]
setting = ["track","gene-other-fwd","several"]
description = """

boolean: if true show 5 per the mini-toggle setting on the other-fwd track.

"""

[setting.other-rev-several]
setting = ["track","gene-other-rev","several"]
description = """

boolean: if true show 5 per the mini-toggle setting on the other-rev track.

"""

[setting.pc-fwd-label]
setting = ["track","gene-pc-fwd","label"]
description = """

boolean: if true show gene label on the pc-fwd track.

"""

[setting.pc-rev-label]
setting = ["track","gene-pc-rev","label"]
description = """

boolean: if true show gene label on the pc-rev track.

"""

[setting.other-fwd-label]
setting = ["track","gene-other-fwd","label"]
description = """

boolean: if true show gene label on the other-fwd track.

"""

[setting.other-rev-label]
setting = ["track","gene-other-rev","label"]
description = """

boolean: if true show gene label on the other-rev track.

"""


[setting.pc-fwd]
setting = ["track","gene-pc-fwd"]
description = """

boolean: if true show the pc-fwd track.

"""

[setting.pc-rev]
setting = ["track","gene-pc-rev"]
description = """

boolean: if true show the pc-rev track.

"""

[setting.other-fwd]
setting = ["track","gene-other-fwd"]
description = """

boolean: if true show the other-fwd track.

"""

[setting.other-rev]
setting = ["track","gene-other-rev"]
description = """

boolean: if true show the other-rev track.

"""
