[core]
boot="boot"
files="begs"

[stick-authority]
startup="sa-startup"
lookup="sa-lookup"

[begs.stick]
startup="sa-startup"
lookup="sa-lookup"

[begs.boot]
boot="boot"

[begs.render]
gene="gene"
gene-overview="gene-overview"
