version: "3"
services:
    backend-hi:
        environment:
            - THREADS=16
            - LO_PORT=1

    backend-lo:
        environment:
            - THREADS=4

    memcached:
        environment:
            - MEMCACHED_MB=512

    syslog:
        build: ../../syslog-container
        ports:
            - 11601
        volumes:
            - ${LOG_DIR:-.}:/logs
        networks:
            - default
        environment:
            - FILE_OWNER
            - FILE_GROUP

    frontend:
        build: ../../peregrine-generic
        ports:
            - 8080:8000
        networks:
            - default
