# REMEMBER to create a .env in this idrectory containing your settings. env.sample is a good starting point.
services:
    #
    # New settings for core services
    #

    backend-hi:
        environment:
            - THREADS=16
            - DEBUG=1
            - LOG_HOST=syslog
            - LOG_PORT=11601
            - STARTUP_WAIT=10
            - TELEGRAF_HOST=telegraf
        volumes:
            - ../../backend-server:/usr/src/app

    backend-lo:
        environment:
            - THREADS=4
            - DEBUG=1
            - LOG_HOST=syslog
            - LOG_PORT=11601
            - STARTUP_WAIT=10
            - TELEGRAF_HOST=telegraf
        volumes:
            - ../../backend-server:/usr/src/app

    memcached:
        environment:
            - MEMCACHED_MB=512

    bump-detector:
        environment:
            - LOG_HOST=syslog
            - LOG_PORT=11601

    #
    # Additional services
    #

    syslog:
        build: ../../syslog-container
        ports:
            - 11601
        volumes:
            - ${LOG_DIR:-.}:/logs
        networks:
            - default
        environment:
            - FILE_OWNER
            - FILE_GROUP

    nginx:
        build: ../../nginx-container
        ports:
            - 80:80
        environment:
            - UPSTREAM=ensembl-2020-gb-flatfiles.s3.eu-west-2.amazonaws.com
            - LOG_HOST=syslog
            - LOG_PORT=11601
            - NGINX_CACHE_SIZE
            - FILE_OWNER
            - FILE_GROUP
            - NGINX_CACHE_DIR
        volumes:
            - ${NGINX_CACHE_DIR:-.}:/cache

    telegraf:
        build: ../../telegraf-container
        ports:
            - 8094:8094
        environment:
            - INFLUX_TOKEN
            - INFLUX_URL
            - INFLUX_ORG
            - INFLUX_BUCKET
            - LOG_HOST=syslog
            - LOG_PORT=11601
        extra_hosts:
            - "host.docker.internal:host-gateway"

    eard-complier:
        image: dockerhub.ebi.ac.uk/ensembl-web/peregrine-eard:latest
        volumes:
            - ../../backend-server:/usr/src/app
        working_dir: /usr/src/app
        tty: true
