WHITESPACE = _{ " " | "\t" }
COMMENT = _{ ";" ~ (!"\n" ~ ANY)* ~ &"\n" }

set = { ASCII_ALPHANUMERIC+ }
version = { (ASCII_DIGIT+) }
identifier = ${ set ~ "/" ~ version }
identifiers = { identifier ~ ("," ~ identifier)* }
header_line = _{ "set:" ~ identifiers ~ "\n" }

opcode = @{ (ASCII_DIGIT)+ ~ &WHITESPACE }
name = { ASCII_ALPHANUMERIC+ }
map_line ={ opcode ~ name ~ "\n" }

section = { header_line ~ ("\n"|map_line)* }

document = { SOI ~ section* ~ EOI }
